service: lineq-solver
frameworkVersion: '3'
configValidationMode: off
provider:
  name: azure
  region: Switzerland North
  runtime: python3.7
  os: linux
  stage: prod

plugins:
  - serverless-azure-functions
  - serverless-offline-python
  - serverless-python-requirements

package:
  exclude:
    - local.settings.json
    - .vscode/**
  patterns:
    - '!env/**'
    - '!.env/**'
    - '!local.settings.json'
    - '!.vscode/**'
    - '!__pycache__/**'
    - '!node_modules/**'
    - '!.python_packages/**'
    - '!.funcignore'
    - '!package.json'
    - '!package-lock.json'
    - '!.gitignore'
    - '!.git/**'

functions:
  solver:
    handler: src/handlers/solver.main
    events:
      - http: true
        methods:
          - POST
        x-azure-settings:
          authLevel: function

custom:
  pythonRequirements:
    zip: true
    slim: true